version: '2'
services:
  elasticsearch:
    image: elasticsearch
    ports:
      - "9300:9300"
      - "9200:9200"

  kibana:
    image: kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
  
