version: '3.1'

services:
  elasticsearch:
    build: elasticsearch/
    ports:
      - "9300:9300"
      - "9200:9200"
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./elasticsearch/data:/usr/share/elasticsearch/data
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"

  kibana:
    build: kibana/
    volumes:
      - ./kibana/config/:/usr/share/kibana/config
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
  
  logstash:
    build: logstash/
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    ports:
      - "5000:5000"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    depends_on:
      - elasticsearch

  riemann:
    build: riemann/
    networks:
      - riemann
    container_name: riemann-server
    ports:
      - "127.0.0.1:5556:5556"
    restart: always

  riemann_health:
    build: riemann_health/
    pid: host
    environment:
      - "affinity:container!=*riemannhealth*"
    volumes:
      - "/etc/hostname:/etc/hostname:ro"
    networks:
      - riemann
    depends_on:
      - riemann


  riemann_dash:
    build: riemann_dash/
    networks:
      - riemann
    volumes:
      - ./riemann_dash/config.rb:/usr/app/riemann_dash/config.rb
    ports:
      - "127.0.0.1:4567:4567"
    depends_on:
      - riemann

networks:
  riemann:
    driver: bridge
